# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Docker'
        repository: 'dockercontainertestfunc'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
      

    - task: AzureFunctionAppContainer@1
      inputs:
        azureSubscription: 'Suscripción de Azure 1(51409fb3-026e-4469-85e0-9b2e9a1892dc)'
        appName: 'func2docker'
        imageName: 'dockercontainertestfunc.azurecr.io/dockercontainertestfunc:$(tag)'

        
  
